version: '3'
services:
    recipe-catalog-app:
        container_name: recipe-catalog-app
        build: ./recipe-catalog-app
        ports:
            - "8080:8080"
        links:
            - recipe-catalog-database
    recipe-catalog-database:
        container_name: recipe-catalog-database
        build: ./recipe-catalog-database
        ports:
            - "27017:27017"
        volumes:
            - /tmp:/data