kind: Service
apiVersion: v1

metadata:
  name: recipe-catalog-app
spec:
  type: NodePort
  selector:
    app: recipe-catalog-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recipe-catalog-app-deployment
  labels:
    app: recipe-catalog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-catalog-app
  template:
    metadata:
      labels:
        app: recipe-catalog-app
    spec:
      containers:
        - name: recipe-catalog-app
          image: localhost:5000/recipe-catalog-app:0.1.0
          env:
            - name: MONGODB_HOST
              value: "recipe-catalog-database"
          ports:
            - containerPort: 8080