kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/sbe75/mongodb/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

kind: Service
apiVersion: v1

metadata:
  name: recipe-catalog-database
spec:
  selector:
    app: recipe-catalog-database
  ports:
    - port: 27017
      targetPort: 27017

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: recipe-catalog-database-controller
  labels:
    app: recipe-catalog-database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: recipe-catalog-database
    spec:
      containers:
        - name: recipe-catalog-database
          image: localhost:5000/recipe-catalog-database:0.1.0
          ports:
            - containerPort: 27017
              hostPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
